### PR TITLE
Add explicit types to avoid compile errors

### PR DESCRIPTION
**Pull request by ShaobinTao**
error CS0411: The type arguments for method

        `System.Linq.Enumerable.Select<TSource, TResult>(this System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, int, TResult>)'

cannot be inferred from the usage. Try specifying the type arguments explicitly

### CODE REVIEW

**Review by steve3003 — COMMENTED** [review]
What version of Unity are you using?
On 5.6.1f1 works fine

**Review by steve3003 — APPROVED** [review]
It seems that is not working in Unity 5.4.5.
I will merge this, thanks.
